-- Add missing nutrients to nutrient_entries table
ALTER TABLE nutrient_entries
  ADD COLUMN IF NOT EXISTS vitamin_a NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS vitamin_b12 NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS vitamin_c NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chromium NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS fluoride NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS iodine NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS molybdenum NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS sodium NUMERIC DEFAULT 0;

-- Add missing nutrients to nutrient_goals table
ALTER TABLE nutrient_goals
  ADD COLUMN IF NOT EXISTS vitamin_a NUMERIC DEFAULT 900,
  ADD COLUMN IF NOT EXISTS vitamin_b12 NUMERIC DEFAULT 2.4,
  ADD COLUMN IF NOT EXISTS vitamin_c NUMERIC DEFAULT 90,
  ADD COLUMN IF NOT EXISTS chromium NUMERIC DEFAULT 35,
  ADD COLUMN IF NOT EXISTS fluoride NUMERIC DEFAULT 4000,
  ADD COLUMN IF NOT EXISTS iodine NUMERIC DEFAULT 150,
  ADD COLUMN IF NOT EXISTS molybdenum NUMERIC DEFAULT 45,
  ADD COLUMN IF NOT EXISTS sodium NUMERIC DEFAULT 2300;

-- Add red_meat column for tracking red meat consumption
ALTER TABLE nutrient_entries
  ADD COLUMN IF NOT EXISTS red_meat NUMERIC DEFAULT 0;

-- Add red_meat column to nutrient_goals table
ALTER TABLE nutrient_goals
  ADD COLUMN IF NOT EXISTS red_meat NUMERIC DEFAULT 0;
