import { useEffect } from 'react';

export default function TermsOfService({ onClose }: { onClose: () => void }) {
  // Close on Esc
  useEffect(() => {
    const handler = (e: KeyboardEvent) => {
      if (e.key === 'Escape') onClose();
    };
    window.addEventListener('keydown', handler);
    return () => window.removeEventListener('keydown', handler);
  }, [onClose]);

  return (
    <div className="fixed inset-0 z-50 flex items-start sm:items-center justify-center bg-black/50 p-0 sm:p-4">
      <div className="bg-gray-800 w-full max-w-2xl h-full sm:max-h-[85vh] overflow-y-auto rounded-none sm:rounded-lg p-6 shadow-2xl">
        <div className="flex items-center justify-between mb-4">
          <h3 className="text-xl font-semibold text-white">Terms of Service</h3>
          <button onClick={onClose} className="text-gray-400 hover:text-white text-xl">
            ✕
          </button>
        </div>

        <div className="space-y-6 text-sm leading-relaxed text-gray-300">
          <section>
            <h4 className="text-lg font-semibold text-white mb-3">1. Acceptance of Terms</h4>
            <p>
              By accessing and using CloudHelper (&quot;the Service&quot;), you agree to be bound by these Terms of
              Service. If you do not agree to these terms, please do not use the Service.
            </p>
          </section>

          <section>
            <h4 className="text-lg font-semibold text-white mb-3">2. Nature of the Service and AI Limitations</h4>
            <p>
              The Service utilizes artificial intelligence to generate text and process information. You acknowledge and
              agree that:
            </p>
            <ul className="ml-6 mt-2 list-disc space-y-1">
              <li>AI can make mistakes, including about people.</li>
              <li>Output generated by the Service may be inaccurate, incomplete, or misleading.</li>
              <li>
                The Service is provided for informational and general use only. It does not constitute professional
                medical, legal, financial, or psychological advice. You are solely responsible for verifying any
                information before relying on it.
              </li>
            </ul>
          </section>

          <section>
            <h4 className="text-lg font-semibold text-white mb-3">3. Third-Party Services and APIs</h4>
            <p>
              The Service integrates APIs provided by third parties, specifically Google (Gemini), Groq, and Notion. By
              using our Service, you acknowledge that your input data may be processed by these providers. Your use of
              the Service is also subject to the respective Terms of Service and Privacy Policies of these third
              parties:
            </p>
            <ul className="mt-3 list-disc space-y-1 pl-6">
              <li>
                <a href="https://ai.google.dev/gemini-api/terms" target="_blank" rel="noopener noreferrer" className="text-blue-400 underline hover:text-blue-300">
                  Google / Gemini Terms of Service
                </a>
              </li>
              <li>
                <a href="https://groq.com/terms-of-use" target="_blank" rel="noopener noreferrer" className="text-blue-400 underline hover:text-blue-300">
                  Groq Terms of Service
                </a>
              </li>
              <li>
                <a href="https://notion.notion.site/Terms-and-Privacy-28ffdd083dc3473e9c2da6ec011b58ac" target="_blank" rel="noopener noreferrer" className="text-blue-400 underline hover:text-blue-300">
                  Notion Terms of Service
                </a>
              </li>
            </ul>
          </section>

          <section>
            <h4 className="text-lg font-semibold text-white mb-3">4. Privacy and Data Processing</h4>
            <p>CloudHelper operates in guest mode: no account or login is required, and no account is created.</p>
            <ul className="ml-6 mt-2 list-disc space-y-1">
              <li>
                API keys you enter are stored <strong>locally in your browser</strong> (localStorage). They are never
                transmitted to or stored on our servers.
              </li>
              <li>
                To generate responses, the text you submit (your message and the context you select, such as Notes,
                Notion pages, or sheets) is sent directly to the AI provider you choose (Google Gemini or Groq).
              </li>
              <li>We do not log, sell, or share your prompts or their content with any third party.</li>
            </ul>
          </section>

          <section>
            <h4 className="text-lg font-semibold text-white mb-3">5. Guest Mode and Local Storage</h4>
            <p>
              In guest mode all data you provide — settings, API keys, uploaded documents, and any other local data —
              is stored on your device only. Clearing your browser&apos;s site data will permanently remove this
              information. CloudHelper has no way to recover it.
            </p>
          </section>

          <section>
            <h4 className="text-lg font-semibold text-white mb-3">6. Uploaded Documents and Retrieval (RAG)</h4>
            <p>
              When you upload a document for retrieval-augmented generation, its content is processed and kept in your
              browser&apos;s local storage (e.g. IndexedDB). Only the relevant excerpts are sent to the AI provider to
              answer your question. Uploaded documents remain on your device and are not stored on our servers.
            </p>
          </section>

          <section>
            <h4 className="text-lg font-semibold text-white mb-3">7. Acceptable Use and User Conduct</h4>
            <p>You agree not to use the Service to:</p>
            <ul className="mt-2 list-disc space-y-1 pl-6">
              <li>Generate, upload, or share content that is illegal, defamatory, harassing, or promotes hate speech and violence.</li>
              <li>
                Input sensitive personal data (including but not limited to health records, financial information, or
                government IDs) into the chat.
              </li>
              <li>Attempt to reverse engineer, scrape, or bypass the safety filters and rate limits of the Service or its underlying APIs.</li>
              <li>Develop malicious software, spam, or phishing campaigns.</li>
            </ul>
          </section>

          <section>
            <h4 className="text-lg font-semibold text-white mb-3">8. Intellectual Property</h4>
            <p>
              You retain your rights to any input (prompts) you provide to the Service. To the extent permitted by law,
              you own the output generated by your specific prompts. CloudHelper retains all rights, title, and
              interest in the platform&apos;s code, design, and proprietary infrastructure.
            </p>
          </section>

          <section>
            <h4 className="text-lg font-semibold text-white mb-3">9. Disclaimer of Warranties</h4>
            <p>
              The Service is provided on an &quot;AS IS&quot; and &quot;AS AVAILABLE&quot; basis. CloudHelper expressly
              disclaims all warranties of any kind, whether express or implied, including but not limited to the implied
              warranties of merchantability, fitness for a particular purpose, and non-infringement. We do not
              guarantee that the Service will be uninterrupted, secure, or error-free.
            </p>
          </section>

          <section>
            <h4 className="text-lg font-semibold text-white mb-3">10. Limitation of Liability</h4>
            <p>
              In no event shall CloudHelper, its developers, or its affiliates be liable for any indirect, incidental,
              special, or consequential damages arising out of or in connection with your use of the Service, the
              AI-generated output, or the inability to use the Service.
            </p>
          </section>

          <section>
            <h4 className="text-lg font-semibold text-white mb-3">11. Modifications to the Service and Terms</h4>
            <p>
              We reserve the right to modify or discontinue the Service at any time without notice. We may also update
              these Terms from time to time. Continued use of the Service after any such changes constitutes your
              consent to the changes.
            </p>
          </section>

          <section>
            <h4 className="text-lg font-semibold text-white mb-3">12. Eligibility and Age Requirement</h4>
            <p>
              The Service is intended for individuals who are at least 18 years old, unless a higher minimum age is set
              by the applicable AI provider&apos;s terms. By using the Service you confirm that you meet this
              requirement. If you are under the applicable age, please do not use the Service.
            </p>
          </section>

          <section>
            <h4 className="text-lg font-semibold text-white mb-3">13. Governing Law</h4>
            <p>
              These Terms shall be governed by and construed in accordance with the laws of Italy. Any disputes arising
              under or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts
              located in Italy.
            </p>
          </section>
        </div>

        <div className="mt-6 flex justify-end border-t border-gray-700 pt-4">
          <button
            onClick={onClose}
            className="rounded bg-gray-700 px-4 py-2 text-sm text-gray-300 hover:bg-gray-600"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
}